"""A module for constant values used inside of FreeCAD Document archives."""

from enum import StrEnum

class SubFile(StrEnum):
    """An enumeration of file names inside of FreeCAD document."""
    
    DOCUMENT_XML = "Document.xml"
    """XML file containing geometric information."""
    GUI_DOCUMENT_XML = "GuiDocument.xml"
    """XML file containing GUI specific information"""
    LINE_COLOR_ARRAY = "LineColorArray"
    POINT_COLOR_ARRAY = "PointColorArray"
    """File with unknown purpose. Can have multiple with an incrementing suffix 
    integer
    """
    SHAPE_APPEARANCE = "ShapeAppearance"
    """File with unknown purpose. Can have multiple with an incrementing suffix 
    integer
    """
    SHAPE_BRP = ".Shape.brp"
    """Suffix of file with unknown purpose."""
    SHAPE_MAP_TXT = ".Shape.Map.txt"
    """Suffix of file with unknown purpose. There is one of these per document 
    object.
    """
    STRING_HASHER_TABLE_TXT = "StringHasher.Table.txt"
    """File with unknown purpose."""
    INTERNAL_SHAPE_BRP = ".InternalShape.brp"
    """Suffix of file with unknown purpose. Some document objects have one."""
    ADD_SUB_SHAPE_BRP = ".AddSubShape.brp"
    """Suffix of file with unknwon purpose."""
    ADD_SUB_SHAPE_MAP_TXT = ".AddSubShape.Map.txt"
    """Suffix of file with unknwon purpose."""
    SUPPRESSED_SHAPE_BRP = ".SuppressedShape.brp"
    """Suffix of file with unknwon purpose."""

class XMLTag(StrEnum):
    BOOL = "Bool"
    CAMERA = "Camera"
    COLOR_LIST = "ColorList"
    CONSTRAINT = "Constrain"
    CONSTRAINT_LIST = "ConstraintList"
    CONSTRUCTION = "Construction"
    CUSTOM_ENUM_LIST = "CustomEnumList"
    DOCUMENT = "Document"
    """Top level xml element."""
    DEP = "Dep"
    """Object dependency element."""
    ELEMENT_MAP = "ElementMap"
    ELEMENT_MAP_2 = "ElementMap2"
    EXPAND = "Expand"
    EXPRESSION_ENGINE = "ExpressionEngine"
    EXTENSIONS = "Extensions"
    """Grouping of Extension elements."""
    EXTENSION = "Extension"
    """Element containing information about an extension of an Object."""
    FLOAT = "Float"
    GEOMETRY = "Geometry"
    GEOMETRY_EXTENSION = "GeoExtension"
    GEOMETRY_EXTENSIONS = "GeoExtensions"
    GEOMETRY_LIST = "GeometryList"
    INTEGER = "Integer"
    """Element containing an integer"""
    LINE_SEGMENT = "LineSegment"
    LINK = "Link"
    LINK_LIST = "LinkList"
    LINK_SUB = "LinkSub"
    LINK_SUB_LIST = "LinkSubList"
    MAP = "Map"
    MATERIAL_LIST = "MaterialList"
    OBJECT = "Object"
    """An element with information about an object."""
    OBJECT_DATA = "ObjectData"
    """Grouping of Object elements with CAD information."""
    OBJECT_DEPENDENCIES = "ObjectDeps"
    """Grouping of Dep object dependency elements."""
    OBJECTS = "Objects"
    """Grouping of ObjectDeps and Object elements with ids."""
    PART = "Part"
    PROPERTIES = "Properties"
    """Grouping of Property elements."""
    PROPERTY = "Property"
    """Property of an Object. Usually has subelements with further definition."""
    PROPERTY_COLOR = "PropertyColor"
    """Stores a color as an ARGB integer"""
    PROPERTY_MATERIAL = "PropertyMaterial"
    PROPERTY_PLACEMENT = "PropertyPlacement"
    PROPERTY_VECTOR = "PropertyVector"
    PYTHON = "Python"
    STRING_HASHER = "StringHasher"
    """Under top level xml element. Can have incrementing suffix integer."""
    STRING = "String"
    SUB = "Sub"
    """Element containing the selection in an enumeration list"""
    TRANSIENT_PROPERTY = "_Property"
    VIEW_PROVIDER = "ViewProvider"
    VIEW_PROVIDER_DATA = "ViewProviderData"
    VISUAL_LAYER = "VisualLayer"
    VISUAL_LAYER_LIST = "VisualLayerList"
    UUID = "Uuid"
    
    def __repr__(self):
        return self.name

class XMLObjectType(StrEnum):
    PART_DESIGN_BODY = "PartDesign::Body"
    PART_DESIGN_PAD = "PartDesign::Pad"
    APP_ORIGIN = "App::Origin"
    APP_LINE = "App::Line"
    APP_PLANE = "App::Plane"
    SKETCHER_SKETCH_OBJECT = "Sketcher::SketchObject"
    
    def __repr__(self):
        return self.name

class XMLGeometryType(StrEnum):
    LINE_SEGMENT = "Part::GeomLineSegment"

class XMLGeometryAttr(StrEnum):
    END_X = "EndX"
    END_Y = "EndY"
    END_Z = "EndZ"
    START_X = "StartX"
    START_Y = "StartY"
    START_Z = "StartZ"

class XMLPropertyType(StrEnum):
    APP_ANGLE = "App::PropertyAngle"
    APP_BOOL = "App::PropertyBool"
    APP_COLOR = "App::PropertyColor"
    APP_COLOR_LIST = "App::PropertyColorList"
    APP_ENUM = "App::PropertyEnumeration"
    APP_EXPRESSION_ENGINE = "App::PropertyExpressionEngine"
    APP_FLOAT = "App::PropertyFloat"
    APP_FLOAT_CONSTRAINT = "App::PropertyFloatConstraint"
    APP_LENGTH = "App::PropertyLength"
    APP_LINK = "App::PropertyLink"
    APP_LINK_SUB = "App::PropertyLinkSub"
    APP_LINK_SUBLIST = "App::PropertyLinkSubList"
    APP_LINK_LIST_HIDDEN = "App::PropertyLinkListHidden"
    APP_MAP = "App::PropertyMap"
    APP_MATERIAL = "App::PropertyMaterial"
    APP_MATERIAL_LIST = "App::PropertyMaterialList"
    APP_PERCENT = "App::PropertyPercent"
    APP_PLACEMENT = "App::PropertyPlacement"
    APP_PRECISION = "App::PropertyPrecision"
    APP_PYTHON_OBJECT = "App::PropertyPythonObject"
    APP_STRING = "App::PropertyString"
    APP_UUID = "App::PropertyUUID"
    APP_VECTOR = "App::PropertyVector"
    
    BAD_TYPE = "BadType"
    
    PART_PART_SHAPE = "Part::PropertyPartShape"
    PART_GEOMETRY_LIST = "Part::PropertyGeometryList"
    
    MATERIALS_MATERIAL = "Materials::PropertyMaterial"
    
    SKETCHER_CONSTRAINT_LIST = "Sketcher::PropertyConstraintList"
    
    def __repr__(self):
        return self.name

class XMLAttr(StrEnum):
    COUNT = "count"
    COUNT_CAPITALIZED = "Count"
    EXPANDED = "expanded"
    EXTENSIONS = "Extensions"
    FILE = "file"
    ID = "id"
    LINE_PATTERN = "linePattern"
    LINE_WIDTH = "lineWidth"
    LINK_SUB = "sub"
    MIGRATED = "migrated"
    NAME = "name"
    NAME_CAPITALIZED = "Name"
    OBJECT = "obj"
    POSITION_X = "Px"
    POSITION_Y = "Py"
    POSITION_Z = "Pz"
    QUAT_0 = "Q0"
    QUAT_1 = "Q1"
    QUAT_2 = "Q2"
    QUAT_3 = "Q3"
    SCHEMA_VERSION = "SchemaVersion"
    PROGRAM_VERSION = "ProgramVersion"
    FILE_VERSION = "FileVersion"
    STRING_HASHER = "StringHasher"
    STATUS = "status"
    TRANSIENT_COUNT = "TransientCount"
    TREE_RANK = "treeRank"
    TYPE = "type"
    TYPE_CAPITALIZED = "Type"
    VALUE = "value"
    VALUE_CAPITALIZED = "Value"
    VISIBLE = "visible"
    
    def __repr__(self):
        return self.name