"""A module for constant values used inside of FreeCAD Document archives."""

from enum import StrEnum

class SubFile(StrEnum):
    """An enumeration of file names inside of FreeCAD document."""
    
    DOCUMENT_XML = "Document.xml"
    """XML file containing geometric information."""
    GUI_DOCUMENT_XML = "GuiDocument.xml"
    """XML file containing GUI specific information"""
    POINT_COLOR_ARRAY = "PointColorArray"
    """File with unknown purpose. Can have multiple with an incrementing suffix 
    integer
    """
    SHAPE_APPEARANCE = "ShapeAppearance"
    """File with unknown purpose. Can have multiple with an incrementing suffix 
    integer
    """
    SHAPE_BRP = ".Shape.brp"
    """Suffix of file with unknown purpose."""
    SHAPE_MAP_TXT = ".Shape.Map.txt"
    """Suffix of file with unknown purpose. There is one of these per document 
    object.
    """
    STRING_HASHER_TABLE_TXT = "StringHasher.Table.txt"
    """File with unknown purpose."""
    INTERNAL_SHAPE_BRP = ".InternalShape.brp"
    """Suffix of file with unknown purpose. Some document objects have one."""
    ADD_SUB_SHAPE_BRP = ".AddSubShape.brp"
    """Suffix of file with unknwon purpose."""
    ADD_SUB_SHAPE_MAP_TXT = ".AddSubShape.Map.txt"
    """Suffix of file with unknwon purpose."""
    SUPPRESSED_SHAPE_BRP = ".SuppressedShape.brp"
    """Suffix of file with unknwon purpose."""

class XMLTag(StrEnum):
    BOOL = "Bool"
    CAMERA = "Camera"
    COLOR_LIST = "ColorList"
    CONSTRAINT = "Constrain"
    CONSTRAINT_LIST = "ConstraintList"
    CONSTRUCTION = "Construction"
    CUSTOM_ENUM_LIST = "CustomEnumList"
    DOCUMENT = "Document"
    """Top level xml element."""
    DEP = "Dep"
    """Object dependency element."""
    ELEMENT_MAP = "ElementMap"
    ELEMENT_MAP_2 = "ElementMap2"
    EXPAND = "Expand"
    EXPRESSION_ENGINE = "ExpressionEngine"
    EXTENSIONS = "Extensions"
    """Grouping of Extension elements."""
    EXTENSION = "Extension"
    """Element containing information about an extension of an Object."""
    GEOMETRY_LIST = "GeometryList"
    GEOMETRY = "Geometry"
    GEOMETRY_EXTENSIONS = "GeoExtensions"
    GEOMETRY_EXTENSION = "GeoExtension"
    INTEGER = "Integer"
    """Element containing an integer"""
    LINE_SEGMENT = "LineSegment"
    LINK = "Link"
    LINK_LIST = "LinkList"
    LINK_SUB = "LinkSub"
    LINK_SUB_LIST = "LinkSubList"
    MAP = "Map"
    MATERIAL_LIST = "MaterialList"
    OBJECT = "Object"
    """An element with information about an object."""
    OBJECT_DATA = "ObjectData"
    """Grouping of Object elements with CAD information."""
    OBJECT_DEPENDENCIES = "ObjectDeps"
    """Grouping of Dep object dependency elements."""
    OBJECTS = "Objects"
    """Grouping of ObjectDeps and Object elements with ids."""
    PART = "Part"
    PRIVATE_PROPERTY = "_Property"
    PROPERTIES = "Properties"
    """Grouping of Property elements."""
    PROPERTY = "Property"
    """Property of an Object. Usually has subelements with further definition."""
    PROPERTY_COLOR = "PropertyColor"
    PROPERTY_MATERIAL = "PropertyMaterial"
    PROPERTY_PLACEMENT = "PropertyPlacement"
    PROPERTY_VECTOR = "PropertyVector"
    STRING_HASHER = "StringHasher"
    """Under top level xml element. Can have incrementing suffix integer."""
    STRING = "String"
    SUB = "Sub"
    """Element containing the selection in an enumeration list"""
    VIEW_PROVIDER = "ViewProvider"
    VIEW_PROVIDER_DATA = "ViewProviderData"
    UUID = "Uuid"

class XMLObjectType(StrEnum):
    PART_DESIGN_BODY = "PartDesign::Body"
    PART_DESIGN_PAD = "PartDesign::Pad"
    APP_ORIGIN = "App::Origin"
    APP_LINE = "App::Line"
    APP_PLANE = "App::Plane"
    SKETCHER_SKETCH_OBJECT = "Sketcher::SketchObject"

class XMLPropertyType(StrEnum):
    APP_ANGLE = "App::PropertyAngle"
    APP_BOOL = "App::PropertyBool"
    APP_ENUM = "App::PropertyEnumeration"
    APP_EXPRESSION_ENGINE = "App::PropertyExpressionEngine"
    APP_FLOAT = "App::PropertyFloat"
    APP_LENGTH = "App::PropertyLength"
    APP_LINK = "App::PropertyLink"
    APP_LINK_SUB = "App::PropertyLinkSub"
    APP_MAP = "App::PropertyMap"
    APP_PERCENT = "App::PropertyPercent"
    APP_PLACEMENT = "App::PropertyPlacement"
    APP_PRECISION = "App::PropertyPrecision"
    APP_PYTHON_OBJECT = "App::PropertyPythonObject"
    APP_STRING = "App::PropertyString"
    APP_UUID = "App::PropertyUUID"
    APP_VECTOR = "App::PropertyVector"
    
    BAD_TYPE = "BadType"
    
    PART_PART_SHAPE = "Part::PropertyPartShape"
    
    MATERIALS_MATERIAL = "Materials::PropertyMaterial"

class XMLAttr(StrEnum):
    ID = "id"
    NAME = "name"
    CAPITALIZED_NAME = "Name"
    STATUS = "status"
    TYPE = "type"
    VALUE = "value"