"""A module for constant values used inside of FreeCAD Document archives."""

from enum import StrEnum

class SubFile(StrEnum):
    """An enumeration of file names inside of FreeCAD document."""
    
    DOCUMENT_XML = "Document.xml"
    """XML file containing geometric information."""
    GUI_DOCUMENT_XML = "GuiDocument.xml"
    """XML file containing GUI specific information"""
    LINE_COLOR_ARRAY = "LineColorArray"
    POINT_COLOR_ARRAY = "PointColorArray"
    """File with unknown purpose. Can have multiple with an incrementing suffix 
    integer
    """
    SHAPE_APPEARANCE = "ShapeAppearance"
    """File with unknown purpose. Can have multiple with an incrementing suffix 
    integer
    """
    SHAPE_BRP = ".Shape.brp"
    """Suffix of file with unknown purpose."""
    SHAPE_MAP_TXT = ".Shape.Map.txt"
    """Suffix of file with unknown purpose. There is one of these per document 
    object.
    """
    STRING_HASHER_TABLE_TXT = "StringHasher.Table.txt"
    """File with unknown purpose."""
    INTERNAL_SHAPE_BRP = ".InternalShape.brp"
    """Suffix of file with unknown purpose. Some document objects have one."""
    ADD_SUB_SHAPE_BRP = ".AddSubShape.brp"
    """Suffix of file with unknwon purpose."""
    ADD_SUB_SHAPE_MAP_TXT = ".AddSubShape.Map.txt"
    """Suffix of file with unknwon purpose."""
    SUPPRESSED_SHAPE_BRP = ".SuppressedShape.brp"
    """Suffix of file with unknwon purpose."""

class Tag(StrEnum):
    """Enumeration of the tags used in FCStd xml files."""
    ARC_OF_CIRCLE = "ArcOfCircle"
    """Element defining the center, orientation, radius, and sweep angles of a 
    sketch circular arc.
    """
    BOOL = "Bool"
    CAMERA = "Camera"
    CIRCLE = "Circle"
    """Element defining the center, orientation, and radius of a sketch circle."""
    COLOR_LIST = "ColorList"
    CONSTRAINT = "Constrain"
    CONSTRAINT_LIST = "ConstraintList"
    CONSTRUCTION = "Construction"
    CUSTOM_ENUM_LIST = "CustomEnumList"
    DOCUMENT = "Document"
    """Top level xml element."""
    DEP = "Dep"
    """Object dependency element."""
    ELLIPSE = "Ellipse"
    """Element defining the center, orientation, and radii of a sketch ellipse."""
    ELEMENT_MAP = "ElementMap"
    ELEMENT_MAP_2 = "ElementMap2"
    EXPAND = "Expand"
    EXPRESSION_ENGINE = "ExpressionEngine"
    EXTENSIONS = "Extensions"
    """Grouping of Extension elements."""
    EXTENSION = "Extension"
    """Element containing information about an extension of an Object."""
    FLOAT = "Float"
    GEOM_POINT = "GeomPoint"
    """Element defining the location of a sketch point."""
    GEOMETRY = "Geometry"
    GEOMETRY_EXTENSION = "GeoExtension"
    GEOMETRY_EXTENSIONS = "GeoExtensions"
    GEOMETRY_LIST = "GeometryList"
    INTEGER = "Integer"
    """Element containing an integer"""
    LINE_SEGMENT = "LineSegment"
    """Element defining the end points of a sketch line segment."""
    LINK = "Link"
    LINK_LIST = "LinkList"
    LINK_SUB = "LinkSub"
    LINK_SUB_LIST = "LinkSubList"
    MAP = "Map"
    MATERIAL_LIST = "MaterialList"
    OBJECT = "Object"
    """An element with information about an object."""
    OBJECT_DATA = "ObjectData"
    """Grouping of Object elements with CAD information."""
    OBJECT_DEPENDENCIES = "ObjectDeps"
    """Grouping of Dep object dependency elements."""
    OBJECTS = "Objects"
    """Grouping of ObjectDeps and Object elements with ids."""
    PART = "Part"
    PROPERTIES = "Properties"
    """Grouping of Property elements."""
    PROPERTY = "Property"
    """Property of an Object. Usually has subelements with further definition."""
    PROPERTY_COLOR = "PropertyColor"
    """Stores a color as an ARGB integer"""
    PROPERTY_MATERIAL = "PropertyMaterial"
    PROPERTY_PLACEMENT = "PropertyPlacement"
    PROPERTY_VECTOR = "PropertyVector"
    PYTHON = "Python"
    STRING_HASHER = "StringHasher"
    """Under top level xml element. Can have incrementing suffix integer."""
    STRING = "String"
    SUB = "Sub"
    """Element containing the selection in an enumeration list"""
    TRANSIENT_PROPERTY = "_Property"
    VIEW_PROVIDER = "ViewProvider"
    VIEW_PROVIDER_DATA = "ViewProviderData"
    VISUAL_LAYER = "VisualLayer"
    VISUAL_LAYER_LIST = "VisualLayerList"
    UUID = "Uuid"
    
    def __repr__(self):
        return f"'{self.value}'"

class XMLObjectType(StrEnum):
    PART_DESIGN_BODY = "PartDesign::Body"
    PART_DESIGN_PAD = "PartDesign::Pad"
    APP_ORIGIN = "App::Origin"
    APP_LINE = "App::Line"
    APP_PLANE = "App::Plane"
    
    def __repr__(self):
        return self.name

class Sketcher(StrEnum):
    """Enumeration of 'Sketcher::' options in FCStd xml files."""
    SKETCH = "Sketcher::SketchObject"
    """type attribute of Sketch Object elements."""
    CONSTRAINT_LIST = "Sketcher::PropertyConstraintList"
    """type attribute of constraint list Property elements."""
    GEOMETRY_EXT = "Sketcher::SketchGeometryExtension"
    """type attribute of sketch GeoExtension elements with sketch specific info 
    stored on them.
    """
    EXTERNAL_EXT = "Sketcher::ExternalGeometryExtension"
    """type attribute of sketch GeoExtension elements. Unknown use."""

class App(StrEnum):
    """Enumeration of 'App::' options in FCStd xml files."""
    ANGLE = "App::PropertyAngle"
    BOOL = "App::PropertyBool"
    COLOR = "App::PropertyColor"
    COLOR_LIST = "App::PropertyColorList"
    ENUM = "App::PropertyEnumeration"
    EXPRESSION_ENGINE = "App::PropertyExpressionEngine"
    FLOAT = "App::PropertyFloat"
    FLOAT_CONSTRAINT = "App::PropertyFloatConstraint"
    LENGTH = "App::PropertyLength"
    LINE = "App::Line"
    LINK = "App::PropertyLink"
    LINK_LIST = "App::PropertyLinkList"
    LINK_SUB = "App::PropertyLinkSub"
    LINK_SUBLIST = "App::PropertyLinkSubList"
    LINK_LIST_HIDDEN = "App::PropertyLinkListHidden"
    MAP = "App::PropertyMap"
    MATERIAL = "App::PropertyMaterial"
    MATERIAL_LIST = "App::PropertyMaterialList"
    ORIGIN = "App::Origin"
    PERCENT = "App::PropertyPercent"
    PLACEMENT = "App::PropertyPlacement"
    PLANE = "App::Plane"
    PRECISION = "App::PropertyPrecision"
    PYTHON_OBJECT = "App::PropertyPythonObject"
    STRING = "App::PropertyString"
    UUID = "App::PropertyUUID"
    VECTOR = "App::PropertyVector"

class Attacher(StrEnum):
    """Enumeration of 'Attacher::' options in FCStd xml files."""
    ATTACH_ENGINE_PLANE = "Attacher::AttachEnginePlane"

class Part(StrEnum):
    """Enumeration of 'Part::' options in FCStd xml files."""
    ARC_OF_CIRCLE = "Part::GeomArcOfCircle"
    CIRCLE = "Part::GeomCircle"
    ELLIPSE = "Part::GeomEllipse"
    LINE_SEGMENT = "Part::GeomLineSegment"
    POINT = "Part::GeomPoint"
    SHAPE = "Part::PropertyPartShape"
    GEOMETRY_LIST = "Part::PropertyGeometryList"

class PartDesign(StrEnum):
    """Enumeration of 'PartDesign::' options in FCStd xml files."""
    BODY = "PartDesign::Body"
    PAD = "PartDesign::Pad"
    REVOLUTION = "PartDesign::Revolution"
    POCKET = "PartDesign::Pocket"
    GROOVE = "PartDesign::Groove"

class Materials(StrEnum):
    """Enumeration of 'Materials::' options in FCStd xml files."""
    MATERIAL = "Materials::PropertyMaterial"

class PropertyType(StrEnum):
    """Enumeration of types that do not have a '::' namespace."""
    BAD_TYPE = "BadType"
    
    def __repr__(self):
        return self.name

class XMLGeometryType(StrEnum):
    """Enumeration of the supported FCStd Geometry element type attributes"""
    ARC_OF_CIRCLE = "Part::GeomArcOfCircle"
    CIRCLE = "Part::GeomCircle"
    ELLIPSE = "Part::GeomEllipse"
    LINE_SEGMENT = "Part::GeomLineSegment"
    POINT = "Part::GeomPoint"

class XMLGeometryAttr(StrEnum):
    END_X = "EndX"
    END_Y = "EndY"
    END_Z = "EndZ"
    START_X = "StartX"
    START_Y = "StartY"
    START_Z = "StartZ"



class Attr(StrEnum):
    """Enumeration of element attribute names in FCStd xml files."""
    COUNT = "count"
    COUNT_CAPITALIZED = "Count"
    ELEMENT_MAP = "ElementMap"
    EXPANDED = "expanded"
    EXTENSIONS = "Extensions"
    FILE = "file"
    HASHER_INDEX = "HasherIndex"
    ID = "id"
    INTERNAL_GEOMETRY_TYPE = "internalGeometryType"
    KEY = "key"
    LINE_PATTERN = "linePattern"
    LINE_WIDTH = "lineWidth"
    LINK_SUB = "sub"
    MIGRATED = "migrated"
    NAME = "name"
    NAME_CAPITALIZED = "Name"
    NEW = "new"
    OBJECT = "obj"
    POSITION_X = "Px"
    POSITION_Y = "Py"
    POSITION_Z = "Pz"
    QUAT_0 = "Q0"
    QUAT_1 = "Q1"
    QUAT_2 = "Q2"
    QUAT_3 = "Q3"
    SCHEMA_VERSION = "SchemaVersion"
    PROGRAM_VERSION = "ProgramVersion"
    FILE_VERSION = "FileVersion"
    SETTINGS = "settings"
    STRING_HASHER = "StringHasher"
    STATUS = "status"
    TRANSIENT_COUNT = "TransientCount"
    TREE_RANK = "treeRank"
    TYPE = "type"
    TYPE_CAPITALIZED = "Type"
    VALUE = "value"
    VALUE_CAPITALIZED = "Value"
    VISIBLE = "visible"
    
    def __repr__(self):
        return f"'{self.value}'"