[general]
# Settings used by pancad application-wide
default_save_path = '%homepath%'

[application_paths]
# Paths to external executables used by pancad
freecad = ''

[svg]
# svg file specific settings
auto_size_margin = 0.1
default_unit = 'mm'
[svg.geometry_style]
[svg.geometry_style.font]
font = ''
font-family = ''
font-size = ''
font-size-adjust = ''
font-stretch = ''
font-style = ''
font-variant = ''
font-weight = ''
[svg.geometry_style.text]
direction = ''
letter-spacing = ''
text-decoration = ''
unicode-bidi = ''
word-spacing = ''
[svg.geometry_style.color_and_paint]
color-interpolation = ''
color-interpolation-filters = ''
color-profile = ''
color-rendering = ''
fill = 'none'
fill-opacity = ''
fill-rule = ''
image-rendering = ''
marker = ''
marker-end = ''
marker-mid = ''
marker-start = ''
shape-rendering = ''
stroke = 'black'
stroke-dasharray = ''
stroke-dashoffset = ''
stroke-linecap = 'butt'
stroke-linejoin = 'miter'
stroke-miterlimit = ''
stroke-opacity = ''
stroke-width = '0.0105px'
text-rendering = ''
[svg.construction_geometry_style]
color-interpolation = ''
color-interpolation-filters = ''
color-profile = ''
color-rendering = ''
fill = 'none'
fill-opacity = ''
fill-rule = ''
image-rendering = ''
marker = ''
marker-end = ''
marker-mid = ''
marker-start = ''
shape-rendering = ''
stroke = 'gray'
stroke-dasharray = 0.1
stroke-dashoffset = ''
stroke-linecap = 'butt'
stroke-linejoin = 'miter'
stroke-miterlimit = ''
stroke-opacity = ''
stroke-width = '0.0105px'
text-rendering = ''
[svg.cad_translation]
point_representation_radius = 0.1